### ISSUE TITLE
Adapt for Tizen OS

### ISSUE THREAD

**Issue by iqsilva** [jhassan8/o-crunchy-tv#3]
Hello friend, why not migrate this to Tizen? Have some plans for it or not? I think if you adapt it will be amazing!!

**Comment by iqsilva** [comment]
i have searched a little https://developer.samsung.com/smarttv/develop/migrating-applications/migrating-legacy-platform-to-tizen.html

**Comment by jhassan8** [comment]
I have a version that had started, I'm going to upload it and see if I can finish it
