### ISSUE TITLE
Create for tizen? 

### ISSUE THREAD

**Issue by Nexow91** [jhassan8/o-crunchy-tv#5]
Create for tizen?  Hi that's a cool app with crunchyroll unfortunately not exist on Samsung tizen TV you can't not create this? I hope so

**Comment by jhassan8** [comment]
Hi, I'm starting to migrate to Tizen but I didn't have time to finish it, I'm going to try to finish and test well on TV

https://github.com/jhassan8/crunchyroll-tizen

When I finish it I change it to public

regards
